input CreateGroupInput {
  avatarURL: String
  groupName: String!
  usersID: [ID!]!
}

input CreateTransactionInput {
  itemName: String!
  itemPrice: Float
}

"""
A date-time string at UTC, such as 2019-12-03T09:54:33Z, compliant with the date-time format.
"""
scalar DateTime

type Group implements Node {
  activeOrder: OrderEdge
  avatarURL: String
  createdAt: DateTime!

  """The globally unique relay ID"""
  globalID: ID!
  groupName: String!
  id: ID!
  members: GroupMemberConnection!
  orders: OrderConnection!
  owner: UserEdge!
  updatedAt: DateTime!
}

type GroupEdge {
  cursor: String
  node: Group
}

type GroupMember implements Node {
  balance: Float!
  createdAt: DateTime!

  """The globally unique relay ID"""
  globalID: ID!
  group: GroupEdge!
  id: ID!
  transactions: TransactionConnection!
  updatedAt: DateTime!
  user: UserEdge!
}

type GroupMemberConnection {
  edges: [GroupMemberEdge!]!
  pageInfo: PageInfo!
}

type GroupMemberEdge {
  cursor: String
  node: GroupMember
}

type Mutation {
  createGroup(createGroupInput: CreateGroupInput!): Group!
  createOrder(groupID: ID!): OrderEdge!
  createTransaction(input: CreateTransactionInput!): TransactionEdge!
  updateOrder(input: UpdateOrderInput!): Order!
  updateTransaction(input: UpdateTransactionInput!): TransactionEdge!
  updateTransactionsMany(input: UpdateTransactionsManyInput!): TransactionConnection!
}

interface Node {
  """The globally unique relay ID"""
  globalID: ID!
}

type Order implements Node {
  createdAt: DateTime!

  """The globally unique relay ID"""
  globalID: ID!
  group: GroupEdge!
  id: ID!
  isActive: Boolean!
  payer: GroupMemberEdge!
  transactions: TransactionConnection!
  updatedAt: DateTime!
}

type OrderConnection {
  edges: [OrderEdge!]
  pageInfo: PageInfo
}

type OrderEdge {
  cursor: String
  node: Order
}

type PageInfo {
  endCursor: String
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String
}

type Query {
  group(id: ID!): Group!
  me: User!
  order(id: ID!): Order!
  transaction(id: ID!): Transaction!
  user(id: ID!): User!
}

type Transaction implements Node {
  createdAt: DateTime!

  """The globally unique relay ID"""
  globalID: ID!
  group: GroupEdge!
  id: ID!
  itemName: String!
  itemPrice: Float
  order: OrderEdge!
  payer: GroupMemberEdge!
  recipient: GroupMemberEdge!
  updatedAt: DateTime!
}

type TransactionConnection {
  edges: [TransactionEdge!]
  pageInfo: PageInfo
}

type TransactionEdge {
  cursor: String
  node: Transaction
}

input UpdateOrderInput {
  id: String!
  isActive: Boolean!
}

input UpdateTransactionInput {
  id: String!
  itemName: String
  itemPrice: Float
}

input UpdateTransactionsManyInput {
  transactions: [UpdateTransactionInput!]!
}

type User implements Node {
  avatarURL: String
  createdAt: DateTime!
  firstName: String!

  """The globally unique relay ID"""
  globalID: ID!
  groups: GroupMemberConnection!
  id: String!
  lastName: String!
  updatedAt: DateTime!
  username: String!
}

type UserEdge {
  cursor: String
  node: User
}
